BASE_DIR="nnet-emotion/finetune"
INPUT_DIR="$BASE_DIR/inputs"
OUTPUT_DIR="$BASE_DIR/outputs"
MODEL_INPUT_DIR="$INPUT_DIR/reference"
MODEL_OUTPUT_DIR="$OUTPUT_DIR/reference"
DATA_OUTPUT_DIR="$OUTPUT_DIR/data"
DATA_OUTPUT_COMBINED_DIR="$OUTPUT_DIR/data/combined"

# this is final.raw generated by the original vox2 
# script (in v2/exp/xvector_nnet_1a/final.raw)
BASE_REFERENCE_MODEL="vox2_base.raw"
MODIFIED_REFERENCE_MODEL="vox2_modified_base.raw"

MUSAN_DIR="corpora/musan"
NOISE_DIR="corpora/RIRS_NOISES"