# this is final.raw generated by the original vox2 
# script (in v2/exp/xvector_nnet_1a/final.raw)
BASE_REFERENCE_MODEL="vox2_base.raw"
MODIFIED_REFERENCE_MODEL="vox2_modified_base.raw"

BASE_DIR="meld"
INPUT_DIR="$BASE_DIR/inputs"
OUTPUT_DIR="$BASE_DIR/outputs"
MODEL_INPUT_DIR="$INPUT_DIR/reference"
MODEL_OUTPUT_DIR="$OUTPUT_DIR/reference"
DATA_INPUT_DIR="$INPUT_DIR/data"
DATA_OUTPUT_DIR="$OUTPUT_DIR/data"
DATA_OUTPUT_TRAIN_DIR="$DATA_OUTPUT_DIR/train"
DATA_OUTPUT_DEV_DIR="$DATA_OUTPUT_DIR/dev"
DATA_OUTPUT_TEST_DIR="$DATA_OUTPUT_DIR/test"